//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class IcraObjectArrayMsg : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/IcraObjectArray";
        public override string RosMessageName => k_RosMessageName;

        public IcraObjectMsg[] objects;

        public IcraObjectArrayMsg()
        {
            this.objects = new IcraObjectMsg[0];
        }

        public IcraObjectArrayMsg(IcraObjectMsg[] objects)
        {
            this.objects = objects;
        }

        public static IcraObjectArrayMsg Deserialize(MessageDeserializer deserializer) => new IcraObjectArrayMsg(deserializer);

        private IcraObjectArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.objects, IcraObjectMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.objects);
            serializer.Write(this.objects);
        }

        public override string ToString()
        {
            return "IcraObjectArrayMsg: " +
            "\nobjects: " + System.String.Join(", ", objects.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
