//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class IcraObjectMsg : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/IcraObject";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public int priority;
        public double x;
        public double y;
        public double th;
        public string type;

        public IcraObjectMsg()
        {
            this.name = "";
            this.priority = 0;
            this.x = 0.0;
            this.y = 0.0;
            this.th = 0.0;
            this.type = "";
        }

        public IcraObjectMsg(string name, int priority, double x, double y, double th, string type)
        {
            this.name = name;
            this.priority = priority;
            this.x = x;
            this.y = y;
            this.th = th;
            this.type = type;
        }

        public static IcraObjectMsg Deserialize(MessageDeserializer deserializer) => new IcraObjectMsg(deserializer);

        private IcraObjectMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.priority);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.th);
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.priority);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.th);
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "IcraObjectMsg: " +
            "\nname: " + name.ToString() +
            "\npriority: " + priority.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nth: " + th.ToString() +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
