//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class MobileRobotPoseMsg : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/MobileRobotPose";
        public override string RosMessageName => k_RosMessageName;

        public int id;
        public double x;
        public double y;
        public double th;

        public MobileRobotPoseMsg()
        {
            this.id = 0;
            this.x = 0.0;
            this.y = 0.0;
            this.th = 0.0;
        }

        public MobileRobotPoseMsg(int id, double x, double y, double th)
        {
            this.id = id;
            this.x = x;
            this.y = y;
            this.th = th;
        }

        public static MobileRobotPoseMsg Deserialize(MessageDeserializer deserializer) => new MobileRobotPoseMsg(deserializer);

        private MobileRobotPoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.th);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.th);
        }

        public override string ToString()
        {
            return "MobileRobotPoseMsg: " +
            "\nid: " + id.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nth: " + th.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
