//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class PrioritySizePairMsg : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/PrioritySizePair";
        public override string RosMessageName => k_RosMessageName;

        public Std.Int32Msg priority;
        public Std.Float64Msg size;

        public PrioritySizePairMsg()
        {
            this.priority = new Std.Int32Msg();
            this.size = new Std.Float64Msg();
        }

        public PrioritySizePairMsg(Std.Int32Msg priority, Std.Float64Msg size)
        {
            this.priority = priority;
            this.size = size;
        }

        public static PrioritySizePairMsg Deserialize(MessageDeserializer deserializer) => new PrioritySizePairMsg(deserializer);

        private PrioritySizePairMsg(MessageDeserializer deserializer)
        {
            this.priority = Std.Int32Msg.Deserialize(deserializer);
            this.size = Std.Float64Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.priority);
            serializer.Write(this.size);
        }

        public override string ToString()
        {
            return "PrioritySizePairMsg: " +
            "\npriority: " + priority.ToString() +
            "\nsize: " + size.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
