//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class RobotTargetPairMsg : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/RobotTargetPair";
        public override string RosMessageName => k_RosMessageName;

        public MobileRobotPoseMsg robot;
        public TargetMsgMsg target;

        public RobotTargetPairMsg()
        {
            this.robot = new MobileRobotPoseMsg();
            this.target = new TargetMsgMsg();
        }

        public RobotTargetPairMsg(MobileRobotPoseMsg robot, TargetMsgMsg target)
        {
            this.robot = robot;
            this.target = target;
        }

        public static RobotTargetPairMsg Deserialize(MessageDeserializer deserializer) => new RobotTargetPairMsg(deserializer);

        private RobotTargetPairMsg(MessageDeserializer deserializer)
        {
            this.robot = MobileRobotPoseMsg.Deserialize(deserializer);
            this.target = TargetMsgMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot);
            serializer.Write(this.target);
        }

        public override string ToString()
        {
            return "RobotTargetPairMsg: " +
            "\nrobot: " + robot.ToString() +
            "\ntarget: " + target.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
