//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class RobotEventMsg : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/RobotEvent";
        public override string RosMessageName => k_RosMessageName;

        public Std.Int32Msg robot_id;
        public Std.StringMsg target_name;
        public Std.StringMsg event_detail;

        public RobotEventMsg()
        {
            this.robot_id = new Std.Int32Msg();
            this.target_name = new Std.StringMsg();
            this.event_detail = new Std.StringMsg();
        }

        public RobotEventMsg(Std.Int32Msg robot_id, Std.StringMsg target_name, Std.StringMsg event_detail)
        {
            this.robot_id = robot_id;
            this.target_name = target_name;
            this.event_detail = event_detail;
        }

        public static RobotEventMsg Deserialize(MessageDeserializer deserializer) => new RobotEventMsg(deserializer);

        private RobotEventMsg(MessageDeserializer deserializer)
        {
            this.robot_id = Std.Int32Msg.Deserialize(deserializer);
            this.target_name = Std.StringMsg.Deserialize(deserializer);
            this.event_detail = Std.StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
            serializer.Write(this.target_name);
            serializer.Write(this.event_detail);
        }

        public override string ToString()
        {
            return "RobotEventMsg: " +
            "\nrobot_id: " + robot_id.ToString() +
            "\ntarget_name: " + target_name.ToString() +
            "\nevent_detail: " + event_detail.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
