//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class TargetMsgMsg : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/TargetMsg";
        public override string RosMessageName => k_RosMessageName;

        public Std.StringMsg type;
        public Std.StringMsg name;
        public Std.Int32Msg priority;
        public Std.BoolMsg to_buffer;

        public TargetMsgMsg()
        {
            this.type = new Std.StringMsg();
            this.name = new Std.StringMsg();
            this.priority = new Std.Int32Msg();
            this.to_buffer = new Std.BoolMsg();
        }

        public TargetMsgMsg(Std.StringMsg type, Std.StringMsg name, Std.Int32Msg priority, Std.BoolMsg to_buffer)
        {
            this.type = type;
            this.name = name;
            this.priority = priority;
            this.to_buffer = to_buffer;
        }

        public static TargetMsgMsg Deserialize(MessageDeserializer deserializer) => new TargetMsgMsg(deserializer);

        private TargetMsgMsg(MessageDeserializer deserializer)
        {
            this.type = Std.StringMsg.Deserialize(deserializer);
            this.name = Std.StringMsg.Deserialize(deserializer);
            this.priority = Std.Int32Msg.Deserialize(deserializer);
            this.to_buffer = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.Write(this.name);
            serializer.Write(this.priority);
            serializer.Write(this.to_buffer);
        }

        public override string ToString()
        {
            return "TargetMsgMsg: " +
            "\ntype: " + type.ToString() +
            "\nname: " + name.ToString() +
            "\npriority: " + priority.ToString() +
            "\nto_buffer: " + to_buffer.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
