//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class manipulationRequest : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/manipulation";
        public override string RosMessageName => k_RosMessageName;

        public Std.Int32Msg id;
        public Std.StringMsg cmd;
        public Geometry.PoseMsg targetPose;

        public manipulationRequest()
        {
            this.id = new Std.Int32Msg();
            this.cmd = new Std.StringMsg();
            this.targetPose = new Geometry.PoseMsg();
        }

        public manipulationRequest(Std.Int32Msg id, Std.StringMsg cmd, Geometry.PoseMsg targetPose)
        {
            this.id = id;
            this.cmd = cmd;
            this.targetPose = targetPose;
        }

        public static manipulationRequest Deserialize(MessageDeserializer deserializer) => new manipulationRequest(deserializer);

        private manipulationRequest(MessageDeserializer deserializer)
        {
            this.id = Std.Int32Msg.Deserialize(deserializer);
            this.cmd = Std.StringMsg.Deserialize(deserializer);
            this.targetPose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.cmd);
            serializer.Write(this.targetPose);
        }

        public override string ToString()
        {
            return "manipulationRequest: " +
            "\nid: " + id.ToString() +
            "\ncmd: " + cmd.ToString() +
            "\ntargetPose: " + targetPose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
