//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class mobileRobotRequest : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/mobileRobot";
        public override string RosMessageName => k_RosMessageName;

        public Std.StringMsg cmd;
        public MobileRobotPoseMsg[] robots;

        public mobileRobotRequest()
        {
            this.cmd = new Std.StringMsg();
            this.robots = new MobileRobotPoseMsg[0];
        }

        public mobileRobotRequest(Std.StringMsg cmd, MobileRobotPoseMsg[] robots)
        {
            this.cmd = cmd;
            this.robots = robots;
        }

        public static mobileRobotRequest Deserialize(MessageDeserializer deserializer) => new mobileRobotRequest(deserializer);

        private mobileRobotRequest(MessageDeserializer deserializer)
        {
            this.cmd = Std.StringMsg.Deserialize(deserializer);
            deserializer.Read(out this.robots, MobileRobotPoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd);
            serializer.WriteLength(this.robots);
            serializer.Write(this.robots);
        }

        public override string ToString()
        {
            return "mobileRobotRequest: " +
            "\ncmd: " + cmd.ToString() +
            "\nrobots: " + System.String.Join(", ", robots.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
