//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class object_srvRequest : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/object_srv";
        public override string RosMessageName => k_RosMessageName;

        public Std.StringMsg cmd;
        public IcraObjectMsg[] objects;

        public object_srvRequest()
        {
            this.cmd = new Std.StringMsg();
            this.objects = new IcraObjectMsg[0];
        }

        public object_srvRequest(Std.StringMsg cmd, IcraObjectMsg[] objects)
        {
            this.cmd = cmd;
            this.objects = objects;
        }

        public static object_srvRequest Deserialize(MessageDeserializer deserializer) => new object_srvRequest(deserializer);

        private object_srvRequest(MessageDeserializer deserializer)
        {
            this.cmd = Std.StringMsg.Deserialize(deserializer);
            deserializer.Read(out this.objects, IcraObjectMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd);
            serializer.WriteLength(this.objects);
            serializer.Write(this.objects);
        }

        public override string ToString()
        {
            return "object_srvRequest: " +
            "\ncmd: " + cmd.ToString() +
            "\nobjects: " + System.String.Join(", ", objects.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
