//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class priSizeRegRequest : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/priSizeReg";
        public override string RosMessageName => k_RosMessageName;

        public PrioritySizePairMsg[] pairs;

        public priSizeRegRequest()
        {
            this.pairs = new PrioritySizePairMsg[0];
        }

        public priSizeRegRequest(PrioritySizePairMsg[] pairs)
        {
            this.pairs = pairs;
        }

        public static priSizeRegRequest Deserialize(MessageDeserializer deserializer) => new priSizeRegRequest(deserializer);

        private priSizeRegRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pairs, PrioritySizePairMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.pairs);
            serializer.Write(this.pairs);
        }

        public override string ToString()
        {
            return "priSizeRegRequest: " +
            "\npairs: " + System.String.Join(", ", pairs.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
