//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class robotTargetSrvResponse : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/robotTargetSrv";
        public override string RosMessageName => k_RosMessageName;

        public Std.Int32Msg result;

        public robotTargetSrvResponse()
        {
            this.result = new Std.Int32Msg();
        }

        public robotTargetSrvResponse(Std.Int32Msg result)
        {
            this.result = result;
        }

        public static robotTargetSrvResponse Deserialize(MessageDeserializer deserializer) => new robotTargetSrvResponse(deserializer);

        private robotTargetSrvResponse(MessageDeserializer deserializer)
        {
            this.result = Std.Int32Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "robotTargetSrvResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
