//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class robotEventSrvResponse : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/robotEventSrv";
        public override string RosMessageName => k_RosMessageName;

        public UnitTaskMsg new_task;

        public robotEventSrvResponse()
        {
            this.new_task = new UnitTaskMsg();
        }

        public robotEventSrvResponse(UnitTaskMsg new_task)
        {
            this.new_task = new_task;
        }

        public static robotEventSrvResponse Deserialize(MessageDeserializer deserializer) => new robotEventSrvResponse(deserializer);

        private robotEventSrvResponse(MessageDeserializer deserializer)
        {
            this.new_task = UnitTaskMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.new_task);
        }

        public override string ToString()
        {
            return "robotEventSrvResponse: " +
            "\nnew_task: " + new_task.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
