//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class robotEventsSrvRequest : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/robotEventsSrv";
        public override string RosMessageName => k_RosMessageName;

        public RobotEventMsg[] events;

        public robotEventsSrvRequest()
        {
            this.events = new RobotEventMsg[0];
        }

        public robotEventsSrvRequest(RobotEventMsg[] events)
        {
            this.events = events;
        }

        public static robotEventsSrvRequest Deserialize(MessageDeserializer deserializer) => new robotEventsSrvRequest(deserializer);

        private robotEventsSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.events, RobotEventMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.events);
            serializer.Write(this.events);
        }

        public override string ToString()
        {
            return "robotEventsSrvRequest: " +
            "\nevents: " + System.String.Join(", ", events.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
