//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Icra2023Pkg
{
    [Serializable]
    public class unitTaskAllocRequest : Message
    {
        public const string k_RosMessageName = "icra2023_pkg/unitTaskAlloc";
        public override string RosMessageName => k_RosMessageName;

        public UnitTaskMsg[] task;

        public unitTaskAllocRequest()
        {
            this.task = new UnitTaskMsg[0];
        }

        public unitTaskAllocRequest(UnitTaskMsg[] task)
        {
            this.task = task;
        }

        public static unitTaskAllocRequest Deserialize(MessageDeserializer deserializer) => new unitTaskAllocRequest(deserializer);

        private unitTaskAllocRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task, UnitTaskMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.task);
            serializer.Write(this.task);
        }

        public override string ToString()
        {
            return "unitTaskAllocRequest: " +
            "\ntask: " + System.String.Join(", ", task.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
